# https://docs.travis-ci.com/user/database-setup/
language: c
dist: trusty
sudo: required
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_install:
  - curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
before_script:
  - psql -U postgres -c 'CREATE EXTENSION postgis'
  - psql -U postgres -c 'CREATE EXTENSION pllua'
  - psql -U postgres -c 'CREATE DATABASE conreality_test'
script:
  - make all && psql -U postgres -d conreality_test -1 -v ON_ERROR_STOP=1 < schema.sql
